apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - name: http
      protocol: TCP
      port: 80
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: testpod
      image: iammithran/newimage:latest
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: testclaim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello 
    spec:
      containers:
        - name: hello
          image: iammithran/newimage:latest
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: "/var/www/html"
            name: mypd
          volumes:
          - name: mypd
          persistentVolumeClaim:
           claimName: testclaim
